### ISSUE TITLE
Is there a way to make this play with Google?

### ISSUE THREAD

**Issue by KipourosV** [maksis/airdcpp-message-emailer#4]
Been trying every possible combination but I can't make it work.
I have created an app password on my google account security page 

Using port 465 I get this error:

airdcpp-message-emailer: SMTP setting validation failed (Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 7sm5869174wrc.81 - gsmtp)

Using port 587 I get:

airdcpp-message-emailer: SMTP setting validation failed (Error: 139837517502272:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
)

Same setup (587) works fine in Ombi....

**Comment by maksis** [comment]
Isn't the SMTP port of Gmail 465? What comes to the credential error, I found various hits for it from Google. I would first try following https://myaccount.google.com/lesssecureapps?pli=1

**Comment by maksis** [comment]
Also see https://community.nodemailer.com/using-gmail/

**Comment by maksis** [comment]
I'm also able to get the same credential error when using port 587. You just need to disable SSL when using a TLS port......

**Comment by KipourosV** [comment]
I have 2fa...
I have created an app password on my google account (as I have done numerous times)
I still get the same errors no matter what combination of port and ssl on/off I try... :(

**Comment by maksis** [comment]
Sorry, this was actually a bug in the extension itself. I'll publish a new version once I've solved a separate compatibility issue with old node.js versions.

**Comment by maksis** [comment]
Released in version 1.0.0
